[package]
name = "dnscat2"
version = "0.1.0"
authors = ["avitex <theavitex@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "~0.5"
bitflags = "~1.2"
tokio = "~0.2"
futures = "~0.3"
futures-timer = "~3.0"
trust-dns-proto = "~0.19"
trust-dns-client = "~0.19"
rand = "~0.7"