[package]
name = "dnscat2"
version = "0.1.0"
authors = ["avitex <theavitex@gmail.com>"]
edition = "2018"

[dependencies]
nom = "~5.1"
bytes = "~0.5"
bitflags = "~1.2"
arrayvec = "~0.5"
futures = "~0.3"
futures-timer = "~2.0"